# Generated by Django 3.2 on 2021-05-02 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACE_Var',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=50)),
                ('alt', models.CharField(max_length=50)),
                ('pos', models.IntegerField()),
                ('impact', models.CharField(max_length=50)),
                ('protein_var', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Virus_var',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=50)),
                ('alt', models.CharField(max_length=50)),
                ('pos', models.IntegerField()),
                ('impact', models.CharField(max_length=50)),
                ('gene', models.CharField(max_length=50)),
                ('protein_var', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Virus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=50000, upload_to='virus/<django.db.models.fields.related.ForeignKey>')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='patient')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('more_infos', models.TextField()),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('predicted', models.BooleanField(default=False)),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ACE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=50000000, upload_to='ace2/<django.db.models.fields.related.ForeignKey>')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='patient')),
            ],
        ),
    ]
